# Generated by Django 4.0.6 on 2022-07-08 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('srl', models.BigAutoField(primary_key=True, serialize=False, verbose_name='지점 연번')),
                ('name', models.TextField(verbose_name='지점명')),
                ('address', models.TextField(verbose_name='지점 주소')),
                ('phone1', models.TextField(validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식이 아닙니다.', regex='\\d{2,3}-?\\d{3,4}-?\\d{4}')], verbose_name='지점 전화번호 1')),
                ('phone2', models.TextField(validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식이 아닙니다.', regex='\\d{2,3}-?\\d{3,4}-?\\d{4}')], verbose_name='지점 전화번호 2')),
            ],
            options={
                'verbose_name': '지점',
            },
        ),
    ]
