# Generated by Django 4.0.6 on 2022-07-18 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('srl', models.BigAutoField(primary_key=True, serialize=False, verbose_name='연번')),
                ('name', models.TextField(verbose_name='지점명')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='올바른 우편번호 형식이 아닙니다.', regex='\\d{5}')], verbose_name='우편번호')),
                ('address1', models.TextField(verbose_name='주소 1')),
                ('address2', models.TextField(verbose_name='주소 2')),
                ('phone1', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식이 아닙니다.', regex='\\d{2,3}-?\\d{3,4}-?\\d{4}')], verbose_name='전화번호 1')),
                ('phone2', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식이 아닙니다.', regex='\\d{2,3}-?\\d{3,4}-?\\d{4}')], verbose_name='전화번호 2')),
            ],
            options={
                'verbose_name': '지점',
            },
        ),
    ]
