# Generated by Django 4.0.6 on 2022-07-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='zip_code',
            new_name='postcode',
        ),
        migrations.AlterField(
            model_name='branch',
            name='address1',
            field=models.TextField(verbose_name='도로명 주소'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address2',
            field=models.TextField(verbose_name='상세 주소'),
        ),
    ]
