# Generated by Django 4.0.6 on 2022-07-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='교시')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='휴일 여부')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('srl', models.BigAutoField(primary_key=True, serialize=False, verbose_name='연번')),
                ('start_datetime', models.DateTimeField(verbose_name='시작 일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료 일시')),
                ('branch_srl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branches.branch', verbose_name='지점 연번')),
                ('user_srl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='이용자 연번')),
            ],
        ),
    ]
